Experiment: Checksum local pod content instead of file modification times
swiftyfinch/Rugby pull request #181
Opened 2022-08-03 20:11 UTC by cltnschlosser

### Description
Hashing whole files is a little bit slower than just hashing the file modification times, but the upside is less cache invalidation.

I have 2 use cases where this is very important:
- CI machines. When they checkout/clone new code the modification dates are updated for directories. I'm experimenting with using rugby in pull request CI which some large local pods that rarely change.
- pod install generated code. This is in a react native project and there they have codegen that happens as a part of pod install, this results in rugby rebuilding 21 pods that haven't actually changed. The timings below are for this project. So we can see the prepare step increases from 2s to 6s, but the 11s build step is skipped completely (7s win! I expect more on the slower CI machines).

Before:
```
[2s] Prepare ✓
[11s] Build ✓
[1s] Integration ✓
[1s] Clean up ✓
[14s] Cached 139/166 pods.
[!] Project size ↓83%
[!] Indexing files count ↓96%
[!] Targets count ↓83%
[14s] Let's roll 🏈
```
With `--experimental-checksum-content`:
```
[6s] Prepare ✓
Build Skip
[1s] Build ✓
[1s] Integration ✓
[1s] Clean up ✓
[7s] Cached 139/166 pods.
[!] Project size ↓83%
[!] Indexing files count ↓96%
[!] Targets count ↓83%
[7s] Let's roll 🏈
```

I've been testing this locally, but I'm not sure how to write test cases for this functionality in the project here, let me know if you have ideas.

Additionally I think the checksumming and file loading can be improved to speed this up a bit, left some comments in that section of the code.

### References
N/A

### Checklist
- [ ] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

❤️ Thanks for contributing to the 🏈 Rugby!

2022-08-04 07:14 UTC, swiftyfinch commented
@cltnschlosser Thanks a lot for this request! It’s a great feature!

It’s pretty similar to the first implementation of the checksum algorithm) Then I changed it in favor of checking date modifications. But I think you are right now and it’s a better solution. I was going to rethink this one, but I didn’t have enough time.

Could we split this request into two separate ones? Like these:
- `nonInteractive` flag
- New experimental checksums algorithm

I think there are two different purposes.
And then will continue reviewing it.

2022-08-04 14:52 UTC, cltnschlosser commented
Created https://github.com/swiftyfinch/Rugby/pull/183 for the `--non-interactive` flag. I'll pull it out of this one shortly.

2022-08-04 15:41 UTC, swiftyfinch requested changes

2022-08-04 15:41 UTC, swiftyfinch commented on Sources/Rugby/Common/Extensions/Crypto/String+SHA1.swift
We can remove `import CommonCrypto` here

2022-08-04 15:41 UTC, swiftyfinch commented on Sources/Rugby/Common/Extensions/Crypto/Data+SHA1.swift
> +//  Created on 8/3/22.
Let's follow the same style from other headers:
```suggestion
//  Created by Colton Schlosser on 03.08.2022.
```

2022-08-04 15:41 UTC, swiftyfinch commented on Sources/Rugby/Commands/Cache/Other/Checksums/ChecksumsProvider.swift
> +    private var shouldChecksumContent: Bool
We can use let here:
```suggestion
    private let shouldChecksumContent: Bool
```

2022-08-04 15:41 UTC, swiftyfinch commented on Sources/Rugby/Commands/Cache/Command/CacheHeader.swift
> +    var experimentalChecksumContent: Bool = false
I'm not sure about flag name, I think may be better to use something like `useContentChecksums`.
But it's not so important for experimental flag, I think we can change it later.

2022-08-04 15:43 UTC, swiftyfinch commented
> I've been testing this locally, but I'm not sure how to write test cases for this functionality in the project here, let me know if you have ideas.

I think we can change tests after flag became non experimental. It's OK for now 👍

2022-08-04 15:44 UTC, cltnschlosser commented on Sources/Rugby/Common/Extensions/Crypto/Data+SHA1.swift
> +//  Created on 8/3/22.
I got a complaint from the spelling check that my name wasn't a word. If I do this exact formatting will it work (I guess I can try)

2022-08-04 16:03 UTC, swiftyfinch commented on Sources/Rugby/Common/Extensions/Crypto/Data+SHA1.swift
> +//  Created on 8/3/22.
You can add it to ignore list `Rugby/.github/scripts/spell_checker_whitelist.yml` 😀

2022-08-04 16:04 UTC, cltnschlosser commented on Sources/Rugby/Common/Extensions/Crypto/Data+SHA1.swift
> +//  Created on 8/3/22.
```
/Users/runner/work/Rugby/Rugby/Sources/Rugby/Common/Extensions/Crypto/Data+SHA1.swift:5:16: warning: Is `colton` typo? (SpellChecker) /Users/runner/work/Rugby/Rugby/Sources/Rugby/Common/Extensions/Crypto/Data+SHA1.swift:5:23: warning: Is `schlosser` typo? (SpellChecker)
```
Any suggestions? I don't have any issue just removing my name from the file.

2022-08-04 16:04 UTC, swiftyfinch commented on Sources/Rugby/Common/Extensions/Crypto/Data+SHA1.swift
> +//  Created on 8/3/22.
Or I can merge it without this spell checking job) And will fix it in main branch later

2022-08-04 16:12 UTC, swiftyfinch commented
OK, everything is fine. Let ship it! 🚀 
I will fix spell checking beyond this request.

2022-08-04 16:12 UTC, swiftyfinch approved these changes

2022-08-04 16:13 UTC, merged

2023-04-18 09:46 UTC, zzzworm commented
Can this feature add to 2.0 version? @swiftyfinch 
After pod install when change branch, there are still some pods will rebuild when use 2.0 version. If there are some low level pods should rebuild(no modified file at all), It also trigger all Pods depends on it to rebuild because of the graph. This may unnecessary and waste time.

2023-04-18 14:32 UTC, swiftyfinch commented
@zzzworm Hello! It's strange. Rugby2.x should compare the content of files and their targets from Pods project.

Do you have some build phase scripts which change your source code?

> Before using 🏈 Rugby you should be sure that your project code base is finalized.
https://github.com/swiftyfinch/Rugby/blob/beta/docs/remote-cache.md

Also, you can generate the yaml files with information about each module checksum.
https://github.com/swiftyfinch/Rugby/issues/220#issuecomment-1458308497
But in the latest version you should use `RUGBY_KEEP_HASH_YAMLS` env variable.

Please, open an new issue/discussion if you still have question about this topic.