fix: Video in README not working
swiftyfinch/Rugby pull request #202
Opened 2022-10-08 12:07 UTC by chedabob

### Description

The video in the README was just showing as the broken file icon on Firefox and Chrome.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/168025/194706682-e77f40a8-71ef-4cd0-bdde-596cb3501792.png">

### Checklist
- [-] I've added at least one test that validates that my change is working, if appropriate
- [-] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [-] I've updated the documentation if necessary

❤️ Thanks for contributing to the 🏈 Rugby!

2022-10-08 13:01 UTC, swiftyfinch requested changes

2022-10-08 13:01 UTC, swiftyfinch commented on README.md
> -  <img src="https://user-images.githubusercontent.com/64660122/141674975-22c970d6-943e-49cc-a86a-42276b3520e8.mp4" width="600"/>
Hello! Thank you for your pull request. I think the better way to change this video to gif.
I already uploaded one. Could you just replace the link?
```
https://user-images.githubusercontent.com/64660122/194708589-7331a02a-6d6e-4c0f-a7ec-e367f7228080.gif
```

2022-10-08 13:09 UTC, swiftyfinch commented
Also, feel free to leave empty checkmarks in todo list. Sometimes it's OK.

2022-10-08 13:12 UTC, swiftyfinch commented
Also, I changed pull request title. It's better to write "What you did in such request", because it will use in the new version changelog.

2022-10-08 14:59 UTC, chedabob commented on README.md
> -  <img src="https://user-images.githubusercontent.com/64660122/141674975-22c970d6-943e-49cc-a86a-42276b3520e8.mp4" width="600"/>
Ah wasn't sure if it was intentional it didn't auto-play. Have updated it to use the Gif.

2022-10-08 15:49 UTC, swiftyfinch requested changes

2022-10-08 15:49 UTC, swiftyfinch commented on README.md
> +![Rugby Demo](https://user-images.githubusercontent.com/64660122/194708589-7331a02a-6d6e-4c0f-a7ec-e367f7228080.gif)
Why we need to change HTML layout and image width here? I don't see any reason for this.
Please, change only the link. All other lines should be kept unchanged.
```suggestion
<p align="center">
   <img src="https://user-images.githubusercontent.com/64660122/194708589-7331a02a-6d6e-4c0f-a7ec-e367f7228080.gif" width="600"/>
</p>
```

2022-10-08 15:52 UTC, swiftyfinch commented on README.md
> -  <img src="https://user-images.githubusercontent.com/64660122/141674975-22c970d6-943e-49cc-a86a-42276b3520e8.mp4" width="600"/>
Yeah, the goal is enable auto-play as it was working in Safari.

2022-10-08 15:54 UTC, swiftyfinch commented on README.md
> +![Rugby Demo](https://user-images.githubusercontent.com/64660122/194708589-7331a02a-6d6e-4c0f-a7ec-e367f7228080.gif)
I made similar changes in my another repository. You can check it out here:
https://github.com/swiftyfinch/Pods/commit/c35db89c480ecfb6d0187cbc78deec8ba8905cf2

2022-10-09 03:16 UTC, swiftyfinch approved these changes

2022-10-09 05:10 UTC, merged

2022-10-12 12:42 UTC, swiftyfinch commented
@chedabob Hey! I see that you don't included in list of 🏈 Rugby contributors.
I think it can be so because you used different (not GitHub) email while committing.
But I see that count of contributors changed. It's pretty strange.

You can read more here or ask GitHub support.
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile