feat: Adding test support to Rugby target, testing VersionParser
swiftyfinch/Rugby pull request #237
Opened 2023-09-30 20:41 UTC by MCanhisares

### Description
Adding test support to the Rugby target, also testing VersionParser class

### References
Helps with #236 

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [NA] I've updated the documentation if necessary

2023-09-30 20:42 UTC, MCanhisares commented on Sources/Rugby/Core/Dependencies/Update/VersionParser.swift
> +enum VersionParserError: LocalizedError {
Made the enum public so other classes are able to reference it directly instead of doing it through VersionParser; can move it back to inside the class if you feel it diverges from the initial proposition

2023-10-01 06:13 UTC, swiftyfinch requested changes

2023-10-01 06:13 UTC, swiftyfinch commented on Sources/Rugby/Core/Dependencies/Update/VersionParser.swift
> +enum VersionParserError: LocalizedError {
Yeah, you are right! I've just added a suggestion with `typealias Error`.

2023-10-01 06:13 UTC, swiftyfinch commented on Package.swift
> +
Let's avoid redundant empty lines

2023-10-01 06:13 UTC, swiftyfinch commented on Tests/RugbyTests/Core/Dependencies/VersionParserTests.swift
> +        XCTAssertEqual(ghVersion.build, parsedVersion.build)
Please, use `// Assert & Act` sections similar to other tests files.
Also, you can skip `self` here.
```suggestion
        let version = "1.0.0"
        let ghVersion = GitHubUpdaterVersion(major: 1, minor: 0, patch: 0, prerelease: GitHubUpdaterVersion.Prerelease.prod, build: 0)
        
        // Act
        let parsedVersion = try self.parser.parse(version)
        
        // Assert
        XCTAssertEqual(ghVersion.major, parsedVersion.major)
        XCTAssertEqual(ghVersion.minor, parsedVersion.minor)
        XCTAssertEqual(ghVersion.patch, parsedVersion.patch)
        XCTAssertEqual(ghVersion.prerelease, parsedVersion.prerelease)
        XCTAssertEqual(ghVersion.build, parsedVersion.build)
```

2023-10-01 06:13 UTC, swiftyfinch commented on Tests/RugbyTests/Core/Dependencies/VersionParserTests.swift
> +            XCTAssertEqual((error as! VersionParserError).localizedDescription, VersionParserError.incorrectVersion(version).localizedDescription)
1. It's better to keep expected value in the beginning of test;
2. We can skip `self` here;
3. It's dangerous to use force unwrap `!` in tests. Here we can use `?` without any problems.
   We sure that expected value isn't nil and anyway we will catch nil error in block.
```suggestion
        let version = "1.0"
        let expectedLocalizedDescription = VersionParserError.incorrectVersion(version).localizedDescription
        
        // Act & Assert
        XCTAssertThrowsError(try parser.parse(version)) { error in
            XCTAssertEqual((error as? VersionParserError).localizedDescription, expectedLocalizedDescription)
```

2023-10-01 06:13 UTC, swiftyfinch commented on Tests/RugbyTests/Core/Dependencies/VersionParserTests.swift
> +//
Swiftlint should send a warning for this header.
I can help to format it if it necessary.

2023-10-01 06:18 UTC, swiftyfinch commented
Thanks a lot for your request! I've added some suggestions.

Please, install SwiftLint `brew install swiftlint` and then you can use `make lint` in the root of fork folder.

I will add swiftlint to SPM package in the future.

2023-10-01 11:26 UTC, swiftyfinch commented
@MCanhisares Hello! Please, rebase your branch on main. I've merged #238.
And run `make lint` for validate source files and format them.

2023-10-01 18:33 UTC, MCanhisares commented on Tests/RugbyTests/Core/Dependencies/VersionParserTests.swift
> +//
No warnings on Swiftlint, what format do you want to follow on this file?

2023-10-01 18:34 UTC, MCanhisares commented
Thanks for the heads up on the changes, managed to fix all of them according to your suggestions, except for the header signature on the test file; let me know what's the format and I'll adjust accordingly

2023-10-01 18:37 UTC, swiftyfinch commented on Tests/RugbyTests/Core/Dependencies/VersionParserTests.swift
> +//
I changed some rules, so let's just delete file header or run `make lint` for this

2023-10-01 18:42 UTC, swiftyfinch commented
> Thanks for the heads up on the changes, managed to fix all of them according to your suggestions, except for the header signature on the test file; let me know what's the format and I'll adjust accordingly

Looks like all lint jobs passed successfully. So, never mind 😅
I will try to figure out what's wrong with rules after the merge.

2023-10-01 18:53 UTC, swiftyfinch approved these changes

2023-10-01 18:56 UTC, swiftyfinch commented
@MCanhisares Everything is fine, but you need to rebase your branch on the swiftyfinch:main

2023-10-02 15:16 UTC, merged