Fix: should use product name instead of module name when patching XCFrameworks
swiftyfinch/Rugby pull request #266
Opened 2023-11-10 22:50 UTC by PRESIDENT810

### Description

When patching support files, we should use just product.name to replace XCFrameworks paths. This is because module name is used for importing modules in swift, which doesn't allow special characters like '-', so for modulemap search path we should use module name; however for header search path and library search path, special characters are allowed. Therefore when we have targets whose name has characters not supported in Swift, such as "foo-bar", using product.moduleName makes the regex pattern for patching XCFrameworks be `"${PODS_XCFRAMEWORKS_BUILD_DIR}/foo_bar"`, which causes search path `"${PODS_XCFRAMEWORKS_BUILD_DIR}/foo-bar"` cannot be substituted because regex pattern doesn't match.

For example:
<img width="923" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/6b2d0691-8226-451d-984b-db23d0637b49">
<img width="1201" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/674558ac-2034-436c-aeec-95fe363f6227">

### Checklist (I have ...)
- [x] 🧐 Followed the code style of the rest of the project
- [ ] 📖 Updated the documentation if necessary
- [x] 👨🏻‍🔧 Added at least one test that validates that my change is working, if appropriate
- [x] 👮🏻‍♂️ Run `make lint` and fixed all warnings
- [x] ✅ Run `make test` and fixed all tests

❤️ Thanks for contributing to the 🏈 Rugby!

2023-11-11 14:29 UTC, swiftyfinch requested changes

2023-11-11 14:29 UTC, swiftyfinch commented on Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
> +                    replacement: "\(binaryFolderPath)/\(name)/\(HEADERS)"
Let's use `product.name` directly in `"\(PODS_XCFRAMEWORKS_BUILD_DIR)\(product.name)/\(HEADERS)"`.
It looks like the `name` is redundant variable.

```suggestion
                    "\(PODS_XCFRAMEWORKS_BUILD_DIR)\(product.name)/\(HEADERS)",
                    replacement: "\(binaryFolderPath)/\(product.name)/\(HEADERS)"
```

2023-11-11 14:29 UTC, swiftyfinch commented on Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
> +                    replacement: "\(binaryFolderPath)/\(name)"
And the same here.

```suggestion
                    "\(PODS_XCFRAMEWORKS_BUILD_DIR)\(product.name)",
                    replacement: "\(binaryFolderPath)/\(product.name)"
```

2023-11-11 14:29 UTC, swiftyfinch commented on Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
> +            let name = product.name
And after that we can remove this line.
```suggestion
```

2023-11-13 18:18 UTC, PRESIDENT810 commented on Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
> +                    replacement: "\(binaryFolderPath)/\(name)/\(HEADERS)"
Fixed

2023-11-13 18:18 UTC, PRESIDENT810 commented on Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
> +                    replacement: "\(binaryFolderPath)/\(name)"
Fixed

2023-11-13 18:18 UTC, PRESIDENT810 commented on Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
> +            let name = product.name
Fixed

2023-11-13 18:19 UTC, PRESIDENT810 commented
@swiftyfinch Ah sorry, wasn't checking GitHub notifications on weekends... I fixed them and now it should be OK.

2023-11-13 18:54 UTC, swiftyfinch approved these changes

2023-11-13 19:08 UTC, merged

2023-11-13 19:39 UTC, swiftyfinch commented
@PRESIDENT810 Thank you for your contribution! 🚀