Fix path replacement issue
swiftyfinch/Rugby pull request #273
Opened 2023-11-18 14:39 UTC by cragod

### Description
I updated the code to use '\b' for match endings, removing the initial boundary (as '\b' at the beginning didn't work). Tested successfully in my project and added relevant unit tests. Further testing may be required.

### References
https://github.com/swiftyfinch/Rugby/issues/271

### Checklist (I have ...)
- [x] 🧐 Followed the code style of the rest of the project
- [ ] 📖 Updated the documentation, if necessary
- [x] 👨🏻‍🔧 Added at least one test which validates that my change is working, if appropriate
- [x] 👮🏻‍♂️ Run `make lint` and fixed all warnings
- [x] ✅ Run `make test` and fixed all tests

❤️ Thanks for contributing to the 🏈 Rugby!

2023-11-19 09:38 UTC, swiftyfinch requested changes

2023-11-19 09:38 UTC, swiftyfinch commented on Sources/RugbyFoundation/Core/Use/FileContentEditor.swift
>  final class FileContentEditor {
Do we need changes in this file except removing redundant `separator` and `tokenPrefix` properties?
I think it's not necessary.

2023-11-19 09:42 UTC, swiftyfinch commented
@cragod First of all, thank you for contribution!

Please, run `make lint` command or fix format issues manually.

I need some time to think about using `\b` and test these changes in my project.
Also, I think that we should add some integration tests to check that RegEx works correctly.
But let me think. I'll be back)

2023-11-19 11:42 UTC, cragod commented on Sources/RugbyFoundation/Core/Use/FileContentEditor.swift
>  final class FileContentEditor {
I extracted a new method to support unit testing for the replacement logic.

2023-11-19 12:04 UTC, cragod commented on Sources/RugbyFoundation/Core/Use/FileContentEditor.swift
>  final class FileContentEditor {
haha, didn't seriously understand the mocking method of File, was careless.

2023-11-19 16:23 UTC, swiftyfinch commented
@cragod It works in my project too ✅

But I also tested RegEx and it's not so strict as it was before.
I think it can be unsuitable in some cases.

<img width="631" alt="Screenshot 2023-11-19 at 19 08 18" src="https://github.com/swiftyfinch/Rugby/assets/64660122/639091b0-7c58-4981-b1db-bc64893821a0">
<br><br>

I have an idea to use `(?=(\"|'|\s))` for suffix. And also, we can add prefix `(?<=(\"|'|\s))`.

<img width="632" alt="Screenshot 2023-11-19 at 19 08 31" src="https://github.com/swiftyfinch/Rugby/assets/64660122/27b3e79c-8056-4049-b1ca-2dce1dc4fb8b">
<br><br>

And finally, I understood why `\b` at the beginning didn't work for you.
There is a such line:
```swift
let prefix = NSRegularExpression.escapedPattern(for: prefix)
```
And it makes special RegEx symbols escaped. So, we need to escape only strings like `BUILT_PRODUCTS_DIR` which passing to the prefix argument, but not `SUFFIX` and `PREFIX` strings.

@cragod Could I ask you to improve your fix based on my thoughts above? Or do you have any doubts?
Anyway, I can improve it by myself if you're not interested in it or don't have enough time. Let me know.

2023-11-19 17:58 UTC, cragod commented
@swiftyfinch I'm glad your test validated my initial concerns. I have adopted your idea to improve my fix. Also, I made some optimizations to quickly adapt to the unit tests in my usual way, let me know if you have any doubts :)

2023-11-20 05:52 UTC, swiftyfinch approved these changes

2023-11-20 08:47 UTC, swiftyfinch commented
> @swiftyfinch I'm glad your test validated my initial concerns. I have adopted your idea to improve my fix. Also, I made some optimizations to quickly adapt to the unit tests in my usual way, let me know if you have any doubts :)

Everything is fine 👍
And I've retested this fix in my project.

2023-11-20 08:47 UTC, merged

2023-11-20 08:47 UTC, swiftyfinch commented
@cragod Thank you for your contribution! 🚀