Fix an error if the default shell is fish.
swiftyfinch/Rugby pull request #77
Opened 2021-11-06 12:49 UTC by kkoudev

Hello. Rugby is very nice tool!
I've found the issue so sent this pull request.

Rugby cache command occurred error if fish shell is default.
I get the following error.

```fish
[2s] Prepare ✓
[1s] Build ✓
[1s] Integration ✓
Clean up Remove schemes
⛔️ Error: fish: Variables cannot be bracketed. In fish, please use {$USER}.
echo ${USER} 
      ^

🚑 Call doctor for more help: rugby doctor
```

This issue seems to be due to the assumption that the shell command is bash or zsh.
Therefore, by pinning the execution shell to bash is resolve this issue.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

2021-11-06 14:30 UTC, swiftyfinch commented
@kkoudev Hello! Thank you for opening the pull request.
I think we just can use `echo $USER` instead of `echo ${USER}` in `XcodeProj+RemoveSchemes` line 63.

2021-11-06 14:33 UTC, swiftyfinch requested changes

2021-11-06 14:33 UTC, swiftyfinch commented on Sources/Rugby/Common/Utils/ShellRunner.swift
> +        let output = SwiftShell.run(bash: "which bash")
Sorry, but we can't use `bash` shell here, because different users can have their own shells.
So we must run all commands in the correct user shell.

2021-11-07 17:30 UTC, kkoudev commented on Sources/Rugby/Common/Utils/ShellRunner.swift
> +        let output = SwiftShell.run(bash: "which bash")
OK. I've fixed to `echo $USER` instead of `echo ${USER}`.

2021-11-07 17:36 UTC, swiftyfinch approved these changes

2021-11-07 17:52 UTC, swiftyfinch commented
@kkoudev Thank you! 🚀

2021-11-07 17:52 UTC, merged